name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      
    - name: Stop docker
      run: sudo docker-compose down
      
    - name: Create network
      run: sudo docker network create external-network
      
    - name: Start docker
      run: sudo docker-compose up
